server:
  port: 8081
spring:
  application:
      name: pcClient
  session:
    #session存储方式
    store-type: redis
  redis:
    host: 127.0.0.1
    port: 6379
    #redis的超时时间
    timeout: 3000
    #设置会话操作后立即更新到redis中,默认是等服务器请求结束后再将变化的值同步到redis中
    flush-mode: immediate
    pool:
      # 连接池中的最大空闲连接
      min-idle: 0
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 8
      # 连接池中的最小空闲连接
      max-wait: -1
#数据源连接信息
  datasource:
    username: root
    password: 123
    url: jdbc:mysql://192.168.2.101:3306/test
    driver-class-name: com.mysql.cj.jdbc.Driver
############################################# Spring Cloud Ribbon 负载均衡配置##########################
eureka:
  client:
    register-with-eureka: false #本微服务为服务消费者，不需要将自己注册到服务注册中心
    fetch-registry: false  #本微服务为服务消费者，需要到服务注册中心搜索服务
    service-url:
      defaultZone: http://localhost:7001/eureka #服务注册单机版