server:
  port: 8081
spring:
  session:
    #session存储方式
    store-type: redis
  redis:
    host: 127.0.0.1
    port: 6379
    #redis的超时时间
    timeout: 3000
    #设置会话操作后立即更新到redis中,默认是等服务器请求结束后再将变化的值同步到redis中
    flush-mode: immediate
    pool:
      # 连接池中的最大空闲连接
      min-idle: 0
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 8
      # 连接池中的最小空闲连接
      max-wait: -1
#数据源连接信息
  datasource:
    username: root
    password: 123
    url: jdbc:mysql://192.168.1.11:3306/test
    driver-class-name: com.mysql.cj.jdbc.Driver
